language: elixir
elixir:
  - 1.2.0
otp_release:
  - 18.0


before_install:
  - docker pull adrienmo/hbase
  - mkdir data
  - id=$(docker run --name=hbase-docker -h hbase-docker -d -v $PWD/data:/data adrienmo/hbase)
  - docker cp migration.sh $id:/migration.sh
  - docker exec -i -t $id /bin/bash /migration.sh
  - ip=$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' $id)
  - echo "hbase server running on $ip"

script:
  - "MIX_ENV=travis mix do deps.get, compile, test"
