%%
%% Autogenerated by Thrift Compiler (0.9.3)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(t_h_base_service_thrift).
-behaviour(thrift_service).


-include("t_h_base_service_thrift.hrl").

-export([struct_info/1, function_info/2]).

struct_info(_) -> erlang:error(function_clause).
%%% interface
% exists(This, Table, Tget)
function_info('exists', params_type) ->
  {struct, [{1, string},
          {2, {struct, {'hbase_types', 'TGet'}}}]}
;
function_info('exists', reply_type) ->
  bool;
function_info('exists', exceptions) ->
  {struct, [{1, {struct, {'hbase_types', 'TIOError'}}}]}
;
% get(This, Table, Tget)
function_info('get', params_type) ->
  {struct, [{1, string},
          {2, {struct, {'hbase_types', 'TGet'}}}]}
;
function_info('get', reply_type) ->
  {struct, {'hbase_types', 'TResult'}};
function_info('get', exceptions) ->
  {struct, [{1, {struct, {'hbase_types', 'TIOError'}}}]}
;
% getMultiple(This, Table, Tgets)
function_info('getMultiple', params_type) ->
  {struct, [{1, string},
          {2, {list, {struct, {'hbase_types', 'TGet'}}}}]}
;
function_info('getMultiple', reply_type) ->
  {list, {struct, {'hbase_types', 'TResult'}}};
function_info('getMultiple', exceptions) ->
  {struct, [{1, {struct, {'hbase_types', 'TIOError'}}}]}
;
% put(This, Table, Tput)
function_info('put', params_type) ->
  {struct, [{1, string},
          {2, {struct, {'hbase_types', 'TPut'}}}]}
;
function_info('put', reply_type) ->
  {struct, []};
function_info('put', exceptions) ->
  {struct, [{1, {struct, {'hbase_types', 'TIOError'}}}]}
;
% checkAndPut(This, Table, Row, Family, Qualifier, Value, Tput)
function_info('checkAndPut', params_type) ->
  {struct, [{1, string},
          {2, string},
          {3, string},
          {4, string},
          {5, string},
          {6, {struct, {'hbase_types', 'TPut'}}}]}
;
function_info('checkAndPut', reply_type) ->
  bool;
function_info('checkAndPut', exceptions) ->
  {struct, [{1, {struct, {'hbase_types', 'TIOError'}}}]}
;
% putMultiple(This, Table, Tputs)
function_info('putMultiple', params_type) ->
  {struct, [{1, string},
          {2, {list, {struct, {'hbase_types', 'TPut'}}}}]}
;
function_info('putMultiple', reply_type) ->
  {struct, []};
function_info('putMultiple', exceptions) ->
  {struct, [{1, {struct, {'hbase_types', 'TIOError'}}}]}
;
% deleteSingle(This, Table, Tdelete)
function_info('deleteSingle', params_type) ->
  {struct, [{1, string},
          {2, {struct, {'hbase_types', 'TDelete'}}}]}
;
function_info('deleteSingle', reply_type) ->
  {struct, []};
function_info('deleteSingle', exceptions) ->
  {struct, [{1, {struct, {'hbase_types', 'TIOError'}}}]}
;
% deleteMultiple(This, Table, Tdeletes)
function_info('deleteMultiple', params_type) ->
  {struct, [{1, string},
          {2, {list, {struct, {'hbase_types', 'TDelete'}}}}]}
;
function_info('deleteMultiple', reply_type) ->
  {list, {struct, {'hbase_types', 'TDelete'}}};
function_info('deleteMultiple', exceptions) ->
  {struct, [{1, {struct, {'hbase_types', 'TIOError'}}}]}
;
% checkAndDelete(This, Table, Row, Family, Qualifier, Value, Tdelete)
function_info('checkAndDelete', params_type) ->
  {struct, [{1, string},
          {2, string},
          {3, string},
          {4, string},
          {5, string},
          {6, {struct, {'hbase_types', 'TDelete'}}}]}
;
function_info('checkAndDelete', reply_type) ->
  bool;
function_info('checkAndDelete', exceptions) ->
  {struct, [{1, {struct, {'hbase_types', 'TIOError'}}}]}
;
% increment(This, Table, Tincrement)
function_info('increment', params_type) ->
  {struct, [{1, string},
          {2, {struct, {'hbase_types', 'TIncrement'}}}]}
;
function_info('increment', reply_type) ->
  {struct, {'hbase_types', 'TResult'}};
function_info('increment', exceptions) ->
  {struct, [{1, {struct, {'hbase_types', 'TIOError'}}}]}
;
% append(This, Table, Tappend)
function_info('append', params_type) ->
  {struct, [{1, string},
          {2, {struct, {'hbase_types', 'TAppend'}}}]}
;
function_info('append', reply_type) ->
  {struct, {'hbase_types', 'TResult'}};
function_info('append', exceptions) ->
  {struct, [{1, {struct, {'hbase_types', 'TIOError'}}}]}
;
% openScanner(This, Table, Tscan)
function_info('openScanner', params_type) ->
  {struct, [{1, string},
          {2, {struct, {'hbase_types', 'TScan'}}}]}
;
function_info('openScanner', reply_type) ->
  i32;
function_info('openScanner', exceptions) ->
  {struct, [{1, {struct, {'hbase_types', 'TIOError'}}}]}
;
% getScannerRows(This, ScannerId, NumRows)
function_info('getScannerRows', params_type) ->
  {struct, [{1, i32},
          {2, i32}]}
;
function_info('getScannerRows', reply_type) ->
  {list, {struct, {'hbase_types', 'TResult'}}};
function_info('getScannerRows', exceptions) ->
  {struct, [{1, {struct, {'hbase_types', 'TIOError'}}},
          {2, {struct, {'hbase_types', 'TIllegalArgument'}}}]}
;
% closeScanner(This, ScannerId)
function_info('closeScanner', params_type) ->
  {struct, [{1, i32}]}
;
function_info('closeScanner', reply_type) ->
  {struct, []};
function_info('closeScanner', exceptions) ->
  {struct, [{1, {struct, {'hbase_types', 'TIOError'}}},
          {2, {struct, {'hbase_types', 'TIllegalArgument'}}}]}
;
% mutateRow(This, Table, TrowMutations)
function_info('mutateRow', params_type) ->
  {struct, [{1, string},
          {2, {struct, {'hbase_types', 'TRowMutations'}}}]}
;
function_info('mutateRow', reply_type) ->
  {struct, []};
function_info('mutateRow', exceptions) ->
  {struct, [{1, {struct, {'hbase_types', 'TIOError'}}}]}
;
% getScannerResults(This, Table, Tscan, NumRows)
function_info('getScannerResults', params_type) ->
  {struct, [{1, string},
          {2, {struct, {'hbase_types', 'TScan'}}},
          {3, i32}]}
;
function_info('getScannerResults', reply_type) ->
  {list, {struct, {'hbase_types', 'TResult'}}};
function_info('getScannerResults', exceptions) ->
  {struct, [{1, {struct, {'hbase_types', 'TIOError'}}}]}
;
% getRegionLocation(This, Table, Row, Reload)
function_info('getRegionLocation', params_type) ->
  {struct, [{1, string},
          {2, string},
          {3, bool}]}
;
function_info('getRegionLocation', reply_type) ->
  {struct, {'hbase_types', 'THRegionLocation'}};
function_info('getRegionLocation', exceptions) ->
  {struct, [{1, {struct, {'hbase_types', 'TIOError'}}}]}
;
% getAllRegionLocations(This, Table)
function_info('getAllRegionLocations', params_type) ->
  {struct, [{1, string}]}
;
function_info('getAllRegionLocations', reply_type) ->
  {list, {struct, {'hbase_types', 'THRegionLocation'}}};
function_info('getAllRegionLocations', exceptions) ->
  {struct, [{1, {struct, {'hbase_types', 'TIOError'}}}]}
;
% checkAndMutate(This, Table, Row, Family, Qualifier, CompareOp, Value, RowMutations)
function_info('checkAndMutate', params_type) ->
  {struct, [{1, string},
          {2, string},
          {3, string},
          {4, string},
          {5, i32},
          {6, string},
          {7, {struct, {'hbase_types', 'TRowMutations'}}}]}
;
function_info('checkAndMutate', reply_type) ->
  bool;
function_info('checkAndMutate', exceptions) ->
  {struct, [{1, {struct, {'hbase_types', 'TIOError'}}}]}
;
function_info(_Func, _Info) -> erlang:error(function_clause).

